name: dev-cicd-tests

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: Test with tox
        run: |
          pip install tox
          tox -- --cov datafog --cov-report xml --cov-report term
      - name: Submit to codecov
        uses: codecov/codecov-action@v3
        if: ${{ matrix.python-version == '3.10' }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: DataFog/datafog-python

      - name: Run script
        env:
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
        run: |
          python datafog/telemetry/open_telemetry.py
