name: feature-cicd-setup-and-test

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:alex-p/tesseract-ocr-devel
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev
          tesseract --version
          dpkg -l | grep tesseract
      - name: Verify Tesseract Installation
        run: |
          which tesseract
          tesseract --list-langs
      - name: Install Dependencies
        run: |
          pip install -U pip
          pip install -e .
          pip install tox just pre-commit
      - name: Run Tests with tox
        run: tox -- --cov datafog --cov-report xml --cov-report term --codeblocks
      - name: Submit to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
